apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      imagePullSecrets:
        - name: buildatscaleregcred
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
          - name: SCM_TYPE
            value: "{{ .Values.global.scm.type }}"
          - name: REGISTRY_TYPE
            value: "{{ .Values.global.registry.type }}"
          - name: SERVICE_TYPE
            value: "{{ .Values.global.ServiceType }}"
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 6000
            name: debug
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 180
            failureThreshold: 200
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 180
            periodSeconds: 10
            failureThreshold: 200
