{{- if eq .Values.global.scm.type "bitbucket" -}}
{{- if not .Values.persistence.existingClaim -}}
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "{{ .Release.Name }}-bitbucket-pvc"
  namespace: {{ .Values.global.NameSpace }}
  annotations:
    {{- if .Values.StorageClass}}
    volume.beta.kubernetes.io/storage-class: "{{ .Values.StorageClass }}"
    {{- end }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{ .Values.persistence.volumeSize }}"
{{- end -}}
{{- end -}}
