{{- if eq .Values.global.scm.type "bitbucket" -}}
{{- if not .Values.persistence.existingClaim -}}
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "{{ .Release.Name }}-bitbucket-pvc"
  namespace: {{ .Values.global.NameSpace }}
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "{{ .Values.persistence.ontap.volumeSize }}"
{{- end -}}
{{- end -}}
