replicaCount: 1
image: docker.bintray.io/jfrog/artifactory-oss:latest
imagePullPolicy: Always
persistence:
  #existingClaim: "<existing-pvc-name>"
  ontap:
    volume: "build_at_scale_artifactory"
    volumeSize: "10000M"
    volumeMountPath: "/build_at_scale_artifactory"
    volumeUID: 0
    volumeGID: 0
