global:
  # "LoadBalancer" or "NodePort"
  ServiceType: NodePort
  # Kubernetes Namespace
  NameSpace: default 
  scm:
    # "gitlab" or "bitbucket"
    type: "gitlab"
  registry:
    # "artifactory" or "docker-registry"
    type: "artifactory"
  version: 1.2
  persistence:
    ontap:
      # ontap data lif IP address
      dataIP: ""
