apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-agent
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
{{- if .Values.Master.SlaveListenerServiceAnnotations }}
  annotations:
{{ toYaml .Values.Master.SlaveListenerServiceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
    - port: {{ .Values.Master.SlaveListenerPort }}
      targetPort: {{ .Values.Master.SlaveListenerPort }}
      name: slavelistener
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
  type: {{ .Values.Master.SlaveListenerServiceType }}
