{{- if eq .Values.global.registry.type "artifactory" -}}
{{- if not .Values.persistence.existingClaim -}}
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "{{ .Release.Name }}-artifactory-pvc"
  namespace: {{ .Values.global.NameSpace }}
  annotations:
    trident.netapp.io/reclaimPolicy: "Retain"
    trident.netapp.io/exportPolicy: "default"
    {{- if .Values.StorageClass}}
    volume.beta.kubernetes.io/storage-class: "{{ .Values.StorageClass }}"
    {{- end }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{ .Values.persistence.volumeSize }}"
{{- end -}}
{{- end -}}
