{{- if eq .Values.global.registry.type "artifactory" -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-artifactory
  namespace: {{ .Values.global.NameSpace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
  type: {{ .Values.global.ServiceType }}
{{- end -}}
