kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-couchdb
  namespace: {{ .Values.global.NameSpace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: couchdb
    port: 5984
    targetPort: 5984
  type: {{ .Values.global.ServiceType }}
