apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
          - name: COUCHDB_USER
            value: "{{ .Values.AdminUser }}"
          - name: COUCHDB_PASSWORD
            value: "{{ .Values.AdminPassword }}"
          volumeMounts:
          - name: {{ .Chart.Name }}
            mountPath: /opt/couchdb/data
          ports:
          - containerPort: 5984
            name: couchdb
          livenessProbe:
            httpGet:
              path: /
              port: couchdb
            initialDelaySeconds: 180
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: couchdb
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 200
      volumes:
        - name: {{ .Chart.Name }}
          persistentVolumeClaim:
            {{- if .Values.persistence.existingClaim }}
            claimName: "{{ .Values.persistence.existingClaim}}"
            {{ else }}
            claimName: "{{ .Chart.Name }}-pvc"
            {{- end -}}
